### ISSUE TITLE
Error on MAC M2 ARM

### ISSUE THREAD

**Issue by M4TxRx** [mpgn/CrackMapExec#6]
**After installation on MAC M2 I have this error :**
`
Traceback`` (most recent call last):
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 805, in get
value = d[option]
~^^^^^^^^
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/init.py", line 1004, in getitem
return self.missing(key) # support subclasses that define missing
^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/init.py", line 996, in missing
raise KeyError(key)
KeyError: 'audit_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/myname/.local/bin/cme", line 5, in
from cme.crackmapexec import main
File "/Users/myname/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/crackmapexec.py", line 17, in
from cme.config import cme_config, cme_workspace, config_log, ignore_opsec
File "/Users/myname/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/config.py", line 18, in
audit_mode = cme_config.get("CME", "audit_mode")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 808, in get
raise NoOptionError(option, section)
configparser.NoOptionError: No option 'audit_mode' in section: 'CME'
`

**Steps to reproduce the behavior:**
git clone https://github.com/mpgn/CrackMapExec
cd CrackMapExec
pipx install . --force
cme

**Crackmapexec info:**

OS: MAC OS ARM Version 13.0.1 (22A400)
Version of CME 6.0.0
Latest release

Version 5.2.3 is OK.

**Comment by QU35T-code** [comment]
It can be related to python3.11 ?

**Comment by mpgn** [comment]
Hello @M4TxRx replace the cme.conf with this one https://github.com/mpgn/CrackMapExec/blob/master/cme/data/cme.conf

By default it's located on ~/.cme/cme.conf :)

**Comment by M4TxRx** [comment]
@mpgn thx a lot it work now !
