### ISSUE TITLE
configparser.NoOptionError: No option 'audit_mode' in section: 'CME'

### ISSUE THREAD

**Issue by sm00v** [mpgn/CrackMapExec#98]
After installing via poetry or pipx I continue to get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/configparser.py", line 805, in get
    value = d[option]
            ~^^^^^^^^
  File "/usr/lib/python3.11/collections/__init__.py", line 1004, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/collections/__init__.py", line 996, in __missing__
    raise KeyError(key)
KeyError: 'audit_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/crackmapexec-pCrBRT9i-py3.11/bin/crackmapexec", line 3, in <module>
    from cme.crackmapexec import main
  File "/root/Tools/CrackMapExec-6.0.1/cme/crackmapexec.py", line 17, in <module>
    from cme.config import cme_config, cme_workspace, config_log, ignore_opsec
  File "/root/Tools/CrackMapExec-6.0.1/cme/config.py", line 18, in <module>
    audit_mode = cme_config.get("CME", "audit_mode")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 808, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'audit_mode' in section: 'CME'
```

I have tried updating and upgrading all packages on the host but no luck.

**Comment by mpgn** [comment]
Remove the folder ~/.cme and rerun cme

**Comment by NeffIsBack** [comment]
> Remove the folder ~/.cme and rerun cme

yep thats the other option :D 
but there should be a fallback now if an option is missing

**Comment by NeffIsBack** [comment]
But i will introduce a proper config upgrade together with #95 so this is hopefully not necessary anymore in the future

**Comment by sm00v** [comment]
> Remove the folder ~/.cme and rerun cme

this worked.....ugh been banging my head for hours lol. thank you!
